from __future__ import annotations

RIESGOS = [
    "diabetes",
    "obesidad",
    "embarazo",
    "enfermedad cardiaca",
    "enfermedad respiratoria",
    "inmunocomprometido",
    "mayor de edad",
]

OBRAS_SOCIALES_BASE = [
    "OSDE",
    "Swiss Medical",
    "Galeno",
    "Medife",
    "Omint",
    "Avalian",
    "Sancor Salud",
    "Luis Pasteur",
    "Hospital Italiano",
    "IOMA",
    "PAMI",
    "OSUTHGRA",
    "OSECAC",
    "OSPE",
    "UP",
    "Particular",
    "Jerarquicos",
    "Federada Salud",
]

ESPECIALIDADES = [
    "Clinica medica",
    "Cardiologia",
    "Pediatria",
    "Traumatologia",
    "Ginecologia",
    "Dermatologia",
    "Neurologia",
    "Cirugia general",
    "Oftalmologia",
    "Psiquiatria",
    "Endocrinologia",
    "Neumonologia",
    "Gastroenterologia",
    "Otorrinolaringologia",
]

ESPECIALIDADES_QUIRURGICAS = {
    "Cirugia general",
    "Traumatologia",
    "Ginecologia",
    "Oftalmologia",
    "Otorrinolaringologia",
}

DIAGNOSTICOS = [
    "control general",
    "hipertension",
    "dolor abdominal",
    "cefalea",
    "gripe",
    "bronquitis",
    "fractura",
    "dermatitis",
    "arritmia",
    "diabetes",
    "ansiedad",
    "dolor lumbar",
    "alergia",
    "asma",
    "gastritis",
    "embarazo",
]

MEDICAMENTOS_BASE = [
    "Paracetamol",
    "Ibuprofeno",
    "Amoxicilina",
    "Metformina",
    "Losartan",
    "Enalapril",
    "Atorvastatina",
    "Omeprazol",
    "Salbutamol",
    "Loratadina",
    "Sertralina",
    "Clonazepam",
    "Insulina NPH",
    "Azitromicina",
    "Diclofenac",
    "Aspirina",
    "Levotiroxina",
    "Prednisona",
    "Furosemida",
    "Amlodipina",
    "Cetirizina",
    "Cefalexina",
    "Fluoxetina",
    "Pantoprazol",
    "Tramadol",
    "Dexametasona",
    "Budesonida",
    "Warfarina",
    "Ranitidina",
    "Domperidona",
]

EFECTOS_BASE = [
    "nauseas",
    "mareos",
    "somnolencia",
    "cefalea",
    "diarrea",
    "constipacion",
    "erupcion cutanea",
    "dolor abdominal",
    "vomitos",
    "vision borrosa",
    "palpitaciones",
    "hipotension",
    "hipertension",
    "insomnio",
    "sequedad bucal",
    "temblores",
    "dolor muscular",
    "fatiga",
    "aumento de peso",
    "perdida de apetito",
    "reaccion alergica",
    "edema",
    "tos seca",
    "sangrado",
    "confusion",
    "urticaria",
    "fotosensibilidad",
    "acidez",
    "hipoglucemia",
    "retencion de liquidos",
    "calambres",
    "ansiedad",
    "irritabilidad",
    "dolor toracico",
    "disnea",
    "fiebre",
    "rinorrea",
    "debilidad",
    "alteracion del gusto",
    "prurito",
    "bradicardia",
    "taquicardia",
    "convulsiones",
    "hepatotoxicidad",
    "nefrotoxicidad",
]

ESTUDIOS_BASE = [
    "Hemograma completo",
    "Radiografia de torax",
    "Electrocardiograma",
    "Ecografia abdominal",
    "Resonancia magnetica",
    "Tomografia computada",
    "Perfil lipidico",
    "Glucemia",
    "Prueba de esfuerzo",
    "Espirometria",
    "Analisis de orina",
    "Ecocardiograma",
    "Endoscopia",
    "Colonoscopia",
    "Audiometria",
    "Fondo de ojo",
]

OPERACIONES_BASE = [
    "Apendicectomia",
    "Colecistectomia",
    "Artroscopia de rodilla",
    "Cesarea",
    "Hernioplastia",
    "Biopsia quirurgica",
    "Cirugia de cataratas",
    "Reduccion de fractura",
    "Amigdalectomia",
    "Laparoscopia exploratoria",
    "Cirugia dermatologica",
    "Colocacion de stent",
]

ROLES_MEDICOS = [
    "ayudante de cirugia",
    "instrumentista",
    "anestesiólogo",
]